from typing import Any, Dict, List

RUNTIME_STATE: Dict[str, Any] = {
    "connection_status": "DISCONNECTED",
    "provider": "BINANCE_WS",
    "symbol": "BTCUSDT",
    "timeframe": "15m",
    "current_price": 0.0,
    "current_signal": "HOLD",
    "signal_score": 0,
    "ai_confidence": 0,
    "risk_status": "UNKNOWN",
    "decision_reasoning": [],
    "invalidating_conditions": [],
    "ema20": 0.0,
    "ema50": 0.0,
    "rsi": 0.0,
    "macd": 0.0,
    "atr": 0.0,
    "support": 0.0,
    "resistance": 0.0,
    "volume": 0.0,
    "volume_ratio": 0.0,
    "position": None,
    "balance": 10000.0,
    "pnl": 0.0,
    "drawdown": 0.0,
    "decision_history": [],
    "market_data_points": 0,
}
